steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - group: "My Group"
    key: "mygroup"
    steps:
      - label: "setup"
      command: echo "Setup ..." && sleep 5
      - label: "execute"
      command: echo "Execute stuff" && sleep 10
      - label: "cleanup"
      command: echo "Cleanup"

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket1"
    key: test
    depends_on: build
    agents:
      size: medium

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test
    agents:
      queue: foo
      size: small
